# Generated by Django 4.1 on 2022-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_attendance_student_details_teacher_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
